name: Deploy Java App to Tencent Cloud

on:
  push:
    branches:
      - main  # 只在 main 分支推送时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # 根据你的项目需求选择合适的 JDK 版本
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package  # 使用 Maven 构建项目

      - name: Create deployment directory
        run: |
          mkdir -p deploy
          cp target/KungFu_Server-1.0.jar deploy/  # 将 JAR 文件复制到 deploy 目录
          cp -r target/lib deploy/     # 将 lib 目录复制到 deploy 目录

      - name: Deploy to Tencent Cloud
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.TENCENT_CLOUD_HOST }}  # 腾讯云服务器 IP
          username: ${{ secrets.TENCENT_CLOUD_USERNAME }}  # 服务器用户名
          key: ${{ secrets.TENCENT_CLOUD_SSH_KEY }}  # SSH 私钥
          source: "deploy/*"  # 上传 deploy 目录下的所有文件
          target: "/opt/myapp/"  # 服务器上的目标路径

      - name: Restart Java Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TENCENT_CLOUD_HOST }}
          username: ${{ secrets.TENCENT_CLOUD_USERNAME }}
          key: ${{ secrets.TENCENT_CLOUD_SSH_KEY }}
          script: |
            cd /opt/myapp
            # 停止正在运行的 Java 应用
            if pgrep -f "KungFu_Server-1.0.jar"; then
              pkill -f "KungFu_Server-1.0.jar"
            fi
            # 启动新的 Java 应用
            nohup java -jar KungFu_Server-1.0.jar > /opt/myapp/logs/app.log 2>&1 &